name: C/C++ CI

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: requirment
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo -E apt-get install git -y
        sudo -E apt-get install gitk git-gui -y
    - name: initial
      run: |
        git submodule update --init --recursive
        sudo chmod a+x Tools/scripts/install-prereqs-ubuntu.sh
        sudo bash Tools/scripts/install-prereqs-ubuntu.sh -y
    - name: build
      run: |
        ./waf configure --board px4-v2
        ./waf rover
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: apm-build
        path: build
        
